% 2020-01-31 Mike Tyszka Create wrapper to call Bob's level1 job setup
% - Blockwise and conditionwise Level 1 run separately
% - Level 1 arguments?

%
% DEBUG:
% Seeing the following messages from preamble in level1 LOIS wrapper:
%   Item fmri_rwls_est: No field(s) named
%   write_residuals
%   Conversion to new syntax: Contrast Manager:F-contrast

% Switch off additional covariates (like duration)
covidx = [];

append2jobname = 'CONTE_LEVEL1_CONDITIONWISE';

root_dir = '/Users/jmt/Data/Conte/Anita_Conte_LOI';
study_dir = fullfile(root_dir, 'sourcedata');
code_dir = fullfile(root_dir, 'code');

matlabbatch = wrapper_level1_lois(covidx, ...
    'studydir',     study_dir, ...
    'subid',        'CC*', ...
    'epipat',       'swua*socnsloi2*.nii', ...
    'nuisancepat',  '*badscan*txt', ...
    'runid',        'EP_task-socnsloi2*bold*', ...
    'behavid',      'sub-CC*socnsloi2*_results.mat', ...
    'basename',     'SOCNS_LOI2', ...
    'model',        '2x3', ...
    'maskthresh',   0.40, ...
    'fcontrast',    1,                      ...
    'pmcontrast',   1,                      ...
    'nskip',        4,                      ...
    'TR',           0.7,                    ...
    'runtest',      0,                      ...
    'doallcon',     1,                      ...
    'is4D',         1,                      ...
    'multisession', 1);

% Save job in code/ directory
jobname = fullfile(code_dir, sprintf('job_pp_%s_%s.mat', strtrim(datestr(now,'mmm_DD_YYYY')), append2jobname));
save(jobname, 'matlabbatch');

% Run job
spm_jobman('initcfg');
spm_jobman('run', matlabbatch);
